### ISSUE TITLE
execute_query()  can't get the lastrowid when insert the record to DB

### ISSUE THREAD

**Issue by Donald-Su** [jkklee/pymysql-pool#13]
Use the function of `execute_query()` to insert the record to DB, can't get lastrowid.

And, the function of `execute_query()` use **with context manager**, so can't use same connection to execute `conn.execute_query("SELECT LAST_INSERT_ID();")`  sentence to query the [LAST_INSERT_ID()](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_last-insert-id).

**Comment by gzwillyy** [comment]
`cur.rowcount` , this return is also useful. 
The version on pypi is 0.3.7, hope to release a new version.

**Comment by jkklee** [comment]
> is also useful.
> The version on pypi is 0.3.7, hope to release a new version.

under consideration

**Comment by jkklee** [comment]
please try v.0.4.3
