### ISSUE TITLE
Avoid Adding Log Handler To The Root Logger

### ISSUE THREAD

**Issue by HH-MWB** [jkklee/pymysql-pool#16]
Hi, shall we move the log handler from the root logger to the logger created in this module?

The current implementation calls `logging.basicConfig`, which will create a handler to root logger. In this approach, other loggers will print to `stderr` after importing this library because of the handler in the root logger.

We can simply resolve this issue by creating the handler in [the logger](https://github.com/jkklee/pymysql-pool/blob/master/pymysqlpool.py#L16) instead of calling `logging.basicConfig` which adds to the root logger. How do you feel about this?

```python
def _add_handler(logger: logging.Logger) -> None:
    handler = logging.StreamHandler()
    handler.setFomatter(
        logging.Formatter(
            fmt="%(asctime)s %(levelname)8s: %(message)s",
            datefmt="%m-%d %H:%M:%S",
        )
    )
    logger.addHandler(handler)

_add_handler(logger)
```

**Comment by jkklee** [comment]
Of course，thanks for your suggestion.  Would you please create a pull request? Tks!

**Comment by jkklee** [comment]
please try v0.4.3
