### ISSUE TITLE
多线程情况下问题

### ISSUE THREAD

**Issue by zjttcsy** [jkklee/pymysql-pool#4]
我实现了连接池单例类，在多线程的情况下，会出现retry_counter没有定义的情况。

**Comment by jkklee** [comment]
方便附上你实现单例的代码段吗

**Comment by SCUTJcfeng** [comment]
```
File "C:\Users\xxxxxxxx\.virtualenvs\xxxxx\lib\site-packages\pymysqlpool.py", line 122, in get_connection
    self._THREAD_LOCAL.retry_counter += 1
AttributeError: '_thread._local' object has no attribute 'retry_counter'
```
我猜应该是在这里报的错, 原因其实跟``threading.local``这个类有关, 在初始化的线程里``_THREAD_LOCAL``才有``retry_counter``这个变量的值, 在其它线程里去访问它的值是访问不到的

**Comment by jkklee** [comment]
@SCUTJcfeng 方便附上你的报错的代码段吗，看你的bugfix能理解，但是我还不太能想明白你的使用场景，什么情况下会不初始化ConnectionPool这个类，而去调用它的实例方法get_connection

**Comment by SCUTJcfeng** [comment]
> @SCUTJcfeng 方便附上你的报错的代码段吗，看你的bugfix能理解，但是我还不太能想明白你的使用场景，什么情况下会不初始化ConnectionPool这个类，而去调用它的实例方法get_connection

```
import threading
import pymysqlpool


pool = pymysqlpool.ConnectionPool(size=2, user='root', password='password')


def print_counter():
    print(pool._THREAD_LOCAL.retry_counter)


def get_conn():
    return pool.get_connection()


def put_conn(conn):
    pool.put_connection(conn)


def print_counter_in_other_threads():
    t1 = threading.Thread(target=print_counter)
    t1.start()
    t1.join()


print_counter()
get_conn()
get_conn()
# put_conn(conn)
print_counter()
print_counter_in_other_threads()
```
不是说不初始化这个类就用, 而是因为这个属性本身是线程安全的, 这个例子就是在其它线程里去访问它的值, 我故意把连接池清空了

**Comment by SCUTJcfeng** [comment]
```
import threading
import pymysqlpool


pool = pymysqlpool.ConnectionPool(size=10, user='root', password='password')


def print_counter():
    print(pool._THREAD_LOCAL.retry_counter)


def print_counter_in_other_threads():
    t1 = threading.Thread(target=print_counter)
    t1.start()
    t1.join()


print_counter()
print_counter_in_other_threads()
```
不是说不初始化这个类就用, 而是因为这个属性本身是线程安全的, 这个例子就是在其它线程里去访问它的值

**Comment by jkklee** [comment]
看明白了，不过retry_counter属性本身就是`Thread-local`的，就是针对每个线程本身的，不同线程的值可能会不一样。
1. 一个线程去访问另一个线程的Thread-local属性，是不是与Thread-local存在的意义相违背了呢
2. 你的修复方法，我觉得可以理解为，一个线程的Thread-local属性，存在被另一个线程“强制修改为0”的可能性

**Comment by SCUTJcfeng** [comment]
@jkklee 不对, 我们是没法修改其它线程的值的, 我理解是在不同的线程里, 这个``retry_counter``的值单独统计是不是?

所以我的修改是针对每个单独的线程``retry_counter``的值的修改, ``_THREAD_LOCAL.retry_counter = 0``这行只会在类的初始化所在的线程里有效(通常是主线程), 在别的线程里第一次访问是没有``retry_counter``的, 所以要给一个初始值0

**Comment by jkklee** [comment]
@SCUTJcfeng
 你访问`pool._THREAD_LOCAL.retry_counter`的意义是什么呢，可以（想）做什么。  
我理解`retry_counter`脱离开`get_connection()`这个动作是没有意义的。你怎么看

**Comment by SCUTJcfeng** [comment]
@jkklee 直接访问是没什么意义的, 但是这个例子本质上跟在``get_connection``里对``retry_counter``的访问是一样的, 这个``retry_counter``确实只在``get_connection``里有意义, 我理解你这样写的原因是防止在不同线程里对同一个变量(``retry_counter``)的访问

**Comment by jkklee** [comment]
@SCUTJcfeng 我试验之后，终于get到你说的问题了😂，这确实是个问题。我之前测测试方法好像是（记不太清了）在主线程`获取链接`，然后把`链接`传给线程的target函数，所以不会从触发这个问题。
我先把你的PR合并进来，但我觉得应该还有更优雅的解法😊

**Comment by rangershs** [comment]
正如SCUTJcfeng所说，threading.local类实例化的线程局部对象，需要在当前线程定义(即赋值)后才能访问，从而在每个线程中为该对象分配内存；如果直接访问该对象，当前线程并没有该对象的定义，那么会出现“object has no attribute”
